StackStorm/PySwitchLib

pyswitch/snmp/SnmpMib.py, pyswitch/snmp/mlx/base/interface.py
pyswitch API for physical  interface admin status enable/disable, get interface admin status using SNMP
UT is done.
=> Mlx 3 sprint 1

pyswitch/SnmpCliDevice.py, pyswitch/device.py, pyswitch/snmp/base/interface.py, pyswitch/snmp/snmpconnector.py
Implemented review comments given as part of PR#98. Since the other branch is common i am not committing directly on that.
=> Implemented review comments given for WIP PR#98

pyswitch/os/slxos/base/cluster.py
Please review and approve the change for management cluster get API
=> Implementation of Management cluster get

pyswitch/os/base/interface.py
Conversational mac additonal properties
=> conversational mac and arp

pyswitch/os/slxos/base/cluster.py
adding df-load-balance in the output
=> Returning deploy and df-load-balance as false if not configured. Also

pyswitch/snmp/mlx/base/interface.py
UT is done for
1) create a VRF with AFI IPv4
2) Delete a VRF 
3) Create a VRF with a AFI IPv6
4) Delete a VRF
=> VRF create and delete for both ipv4/v6

pyswitch/os/base/interface.py, pyswitch/os/slxos/base/interface.py, pyswitch/snmp/mlx/base/interface.py
Create and Delete VE changes for MLX.
Due to merge conflicts and branch issues I am creating a new PR. Please refer to PR below for comments and test cases.
https://github.com/StackStorm/PySwitchLib/pull/158/
=> Create/Delete VE changes for MLX

pyswitch/snmp/mlx/base/interface.py
Fix for defects MLX-65, MLX-70, MLX-71, MLX-72.
Also review the Network essentials PR:
https://github.com/StackStorm/network_essentials/pull/187
=> Fix for defects MLX-65, MLX-70, MLX-71, MLX-72

pyswitch/snmp/base/acl/macacl.py
Tuned the validation for following parameters of MAC ACL:
source
dst
vlan
arp_guard
=> MLX-95 Tuned parameter validation for mac ACL.

pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/base/acl/ipacl.py, pyswitch/snmp/base/acl/macacl.py, pyswitch/snmp/mlx/base/acl/acl.py, pyswitch/snmp/mlx/base/acl/acl_template.py
Made acl_type as optional parameter.
Added additional validations observed during implementation.
=> MLX-96 MLX-97

pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/mlx/base/acl/acl.py
Added code to through exception if parameter passed by user is not supported by the platform.
=> MLX-137: Fix for unsupported parameters as asked in defect.

pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/base/acl/aclparam_parser.py, pyswitch/snmp/base/acl/ipacl.py, pyswitch/snmp/base/acl/ipv6acl.py, pyswitch/snmp/base/acl/macacl.py, pyswitch/snmp/mlx/base/acl/acl.py
MLX-165
MLX-163
MLX-162
MLX-153
=> Fixes for:

pyswitch/snmp/mlx/base/interface.py, pyswitch/utilities.py
UT results is uploaded in defect MLX-108
=> Added a user support to give po as a memberport for  access port in MLX

pyswitch/os/base/interface.py
1.support added configure rt/rd/l3vni under vrf on SLXOS platforms
=> CANDY-881-pys: Changes to accomadate SLXOS configs on vrf

pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/base/acl/aclparam_parser.py, pyswitch/snmp/base/acl/ipacl.py, pyswitch/snmp/base/acl/ipv6acl.py, pyswitch/snmp/base/acl/macacl.py, pyswitch/snmp/mlx/base/acl/acl.py
=> Following MLX defects are fixed as part of this commit:

pyswitch/os/base/interface.py
Invoke SLX APIs for ipv6 link local and arp supp
=> CANDY-930:Invoke right api for IPV6 link local and arp supp

pyswitch/snmp/base/acl/aclparam_parser.py, pyswitch/snmp/mlx/base/acl/acl.py
Fixed issue for log and mirror parameters
On MLX platform, acl_type is not accepted accepted for MAC ACL. Raised exception if provided by user.
=> MLX-190 MLX-179

pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/mlx/base/acl/acl.py
MLX-198 – Fixed in process_cli_output() by checking message in output lines
MLX-99 - Fixed in process_cli_output() by returning on first hit of for loop
=> Updated process_cli_output and apply_acl intf_type check

pyswitch/snmp/base/acl/aclparam_parser.py, pyswitch/snmp/base/acl/ipacl.py, pyswitch/snmp/base/acl/ipv6acl.py, pyswitch/snmp/base/acl/params_validator.py, pyswitch/snmp/mlx/base/acl/acl.py, pyswitch/snmp/mlx/base/acl/acl_template.py
MLX-224
MLX-225
MLX-227
MLX-200
MLX-213
MLX-214
MLX-206
MLX-205
=> Acl pyswitch 15 dec 1

pyswitch/snmp/base/acl/ipacl.py, pyswitch/snmp/base/acl/macacl.py, pyswitch/snmp/mlx/base/acl/acl.py
Following defects are fixed:
MLX-203
MLX-184
MLX-181
MLX-104
MLX-105
=> MLX Defect fixes 

pyswitch/raw/nos/base/acl/acl.py, pyswitch/raw/slx_nos/acl/acl.py, pyswitch/raw/slx_nos/acl/acl_template.py, pyswitch/raw/slxos/base/acl/acl.py, pyswitch/snmp/base/acl/aclparam_parser.py, pyswitch/snmp/base/acl/ipacl.py
MLX-225: Fixed typo
MLX-250: Added a check for log param to be not none. As st2 passes parameters as None if user doesn't specify it.
CANDY-927: Added interface validation check before applying or removing acl on the interface.
=> Acl pyswitch Commits

pyswitch/raw/base/acl.py, pyswitch/raw/nos/base/acl/acl.py, pyswitch/raw/nos/base/acl/acl_template.py, pyswitch/raw/slx_nos/acl/acl.py, pyswitch/raw/slx_nos/acl/acl_template.py, pyswitch/raw/slx_nos/acl/aclparam_parser.py, pyswitch/raw/slx_nos/acl/params_validator.py, pyswitch/raw/slxos/base/acl/acl.py, pyswitch/raw/slxos/base/acl/acl_template.py, pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/base/acl/aclparam_parser.py, pyswitch/snmp/base/acl/params_validator.py, pyswitch/snmp/mlx/base/acl/acl.py
Added multiple rules to already created ipv4 access-list.
The changes are only in PySwitchLib, corresponding network_essentials will be committed separately.
=> IPv4 rules bulking for NOS device type for pyswitch.

pyswitch/raw/base/acl.py, pyswitch/raw/nos/base/acl/acl.py, pyswitch/raw/slx_nos/acl/acl.py, pyswitch/raw/slx_nos/acl/params_validator.py, pyswitch/raw/slxos/base/acl/acl.py, pyswitch/raw/slxos/base/acl/acl_template.py
Supported device types: SLX and VDX
=> Added code to allow bulk rule additions to ipv6 access-lists

pyswitch/raw/slx_nos/acl/params_validator.py, pyswitch/raw/slxos/ver_17s/acl.py, pyswitch/raw/slxos/ver_17s/acl_template.py
slxos_ver17 inherits Nos behavior, overwriting add_l2_acl_rule method in
derived class as it is different than the base class.
=> CANDY-865:

pyswitch/raw/slxos/base/acl/acl.py
Minor mistake that user_data was not returned in case of standard acl.
=> CANDY-1022

pyswitch/snmp/mlx/base/interface.py
=> valid l2 interface type is added for NI

pyswitch/raw/nos/base/acl/acl_template.py, pyswitch/raw/slxos/base/acl/acl_template.py, pyswitch/raw/slxos/ver_17s/acl_template.py
=> Candy- 921

pyswitch/raw/nos/base/acl/acl.py, pyswitch/raw/slx_nos/acl/params_validator.py, pyswitch/raw/slxos/base/acl/acl.py, pyswitch/raw/slxos/ver_17s/acl.py, pyswitch/raw/slxos/ver_17s/aclparam_parser.py, pyswitch/snmp/base/acl/params_validator.py
Added code to check supported parameters for standard l2 acl rule.
=> CANDY-860:

pyswitch/raw/base/acl.py, pyswitch/raw/nos/base/acl/acl.py, pyswitch/raw/slx_nos/acl/acl.py, pyswitch/raw/slxos/base/acl/acl.py, pyswitch/raw/slxos/ver_17s/acl.py, pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/mlx/base/acl/acl.py
https://stackstorm.atlassian.net/browse/MLX-263
This should be fixed now.
=> Removing logging from acl code

pyswitch/raw/slxos/ver_17s/aclparam_parser.py
Fix for apply acl on ethernet interface.
=> CANDY-1053

pyswitch/raw/nos/base/acl/acl.py
Added code to error out if remove_acl fails on interface.
=> CANDY-872: Nos device type

pyswitch/snmp/base/acl/params_validator.py, pyswitch/snmp/mlx/base/acl/acl.py
Following actions are executed:
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.37.73.148 username=admin password=admin acl_name=ext-l2-acl-bulk  acl_rules='[{"action": "deny", "source": "1111.1111.1111", "src_mac_addr_mask": "1111.1111.1111", "dst": "1111.1111.1111", "dst_mac_addr_mask": "1111.1111.1111"}, {"action": "deny", "source": "1111.1111.1112", "src_mac_addr_mask": "1111.1111.1112", "dst": "1111.1111.1112", "dst_mac_addr_mask": "1111.1111.1112"}, {"action": "deny", "source": "1111.1111.1113", "src_mac_addr_mask": "1111.1111.1113", "dst": "1111.1111.1113", "dst_mac_addr_mask": "1111.1111.1113"}]'
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.37.73.148 username=admin password=admin acl_name=ext-l2-acl-bulk  delete=True seq_id="10,40-60"
st2 run …
=> L2 Rule bulking for MLL device.

pyswitch/snmp/mlx/base/acl/acl.py
Following actions executed:
st2 run network_essentials.add_ipv6_rule_acl mgmt_ip=10.37.73.148 username=admin password=admin acl_name=ext-ipv6-acl-bulk  acl_rules='[{"action": "deny", "source": "3001::1/64", "destination": "4001::1/64", "protocol_type": "tcp"}, {"action": "deny", "source": "3001::2/64", "destination": "4001::2/64", "protocol_type": "tcp"}]'
st2 run network_essentials.delete_ipv6_rule_acl mgmt_ip=10.37.73.148 username=admin password=admin acl_name=ext-ipv6-acl-bulk seq_id="20-"
st2 run network_essentials.delete_ipv6_rule_acl mgmt_ip=10.37.73.148 username=admin password=admin acl_name=ext-ipv6-acl-bulk seq_id="all"
=> IPv6 rule bulking added for MLXe device type.

pyswitch/raw/slx_nos/acl/ipxacl.py
Changes to allow 'ipv6' and 'ipv6-icmp' protocol_type.
=> CANDY-1010

pyswitch/raw/slx_nos/acl/ipxacl.py
=> CANDY-1078

pyswitch/os/base/bgp.py
When the user deletes a leaf from the fabric and re-adds the switch back to the fabric, if there is a change in the ASN number for the newly added switch, it needs to be updated on the spine.
=> CANDY-1000

pyswitch/snmp/mlx/base/interface.py
Logs:
ubuntu@st2vagrant:~$ st2 run network_essentials.create_l2_port_channel intf_type=ethernet ports=4/11,4/12,4/13,4/14 port_channel_id=103 mgmt_ip=10.24.85.107 username=admin password=admin port_channel_desc="po103"
..........
id: 5aa88eb7c4da5f214afc71cc
parameters: 
port_channel_desc: po103
port_channel_id: '103'
ports:
- 4/11
- 4/12
- 4/13
- 4/14
result: 
exit_code: 0
result:
port_channel_configs: true
pre_validation: true
stderr: 'st2.actions.python.CreatePortChannel: DEBUG    Creating new Client object.
st2.actions.python.CreatePortChannel: DEBUG    Retrieving value from the datastore …
=> MLX-372: Deploy the LAG for already existing LAG which is not deployed

pyswitch/raw/slxos/base/interface.py, pyswitch/raw/slxos/base/template.py
Bulk switch interfaces to shut/no-shut
=> CANDY-1091: NetConf Bulking intf shut/no-shut to make switch add faster for cedar devices

pyswitch/raw/base/acl.py, pyswitch/raw/slx_nos/acl/acl.py, pyswitch/raw/slx_nos/acl/params_validator.py, pyswitch/snmp/base/acl/acl.py, pyswitch/snmp/base/acl/params_validator.py, pyswitch/snmp/mlx/base/acl/acl.py, requirements.txt
Initial commit for get_acl_rules. This commit works for
MLX L2 and IP acl and for slx and vdx series.
Mapping for slx and vdx series to parameters of action is still due.
=> CANDY-1071

pyswitch/os/base/interface.py, pyswitch/os/slxos/base/interface.py
missing as per EVD .. supress arp and nd on bd
=> arp and nd supp on bd

pyswitchlib/pyswitchlib_api_daemon.py
Fix for host name inline with fix for execute_cli. Refer
https://github.com/StackStorm/network_essentials/pull/382
=> MLX-401 hostname fix for MLX

pyswitch/RestDevice.py
The issue is when some SLX and VDX devices are upgraded the python scritps dont get upgraded and hence there are failures. To avoid this we're using netmiko to make calls to fetch the Chassis Model, since its not available through netconf.
=> Fetch model using netmiko instead of using runCmd

pyswitch/snmp/mlx/base/acl/acl.py
Command
------------
st2 run network_essentials.get_acl_rules mgmt_ip=10.37.73.148 acl_name="mlx-1071"
Output
---------
...
id: 5b02a0bfe3c93b194e0e515f
parameters:
acl_name: mlx-1071
mgmt_ip: 10.37.73.148
result:
exit_code: 0
result: '[{"seq_id": "10", "dst": "any", "vlan": "40", "mirror": "True", "source": "any", "ethertype": "ipv4-l5", "action": "permit"}, {"seq_id": "20", "dst": "any", "vlan": "40", "mirror": "True", "source": "any", "ethertype": "ipv4-l5", "action": "permit"}, {"seq_id": "30", "dst": "any", "vlan": "40", "mirror": "True", "source": "any", "ethertype": "ipv4-l5", "action": "permit"}]'
=> MLX get_acl_rules for ipv6 code is added.
