docs/modules.rst
pyswitch/NetConfDevice.py
pyswitch/os/base/interface.py
pyswitch/os/slxos/base/bgp.py

There is no reason to include logging in the wrapper code. The approach
would be to raise Exceptions appropriate to the api

Remove logging from pyswitch wrapper.

---

pyswitch/SnmpCliDevice.py
pyswitch/device.py

Added SNMPv3 support for SNMP CLI device creation.  Testing was done as part of the testcases mentioned in https://github.com/StackStorm/network_essentials/pull/185

Snmpv3 support

---

pyswitch/snmp/base/acl/acl.py
pyswitch/snmp/base/acl/macacl.py
pyswitch/snmp/mlx/base/acl/acl.py
pyswitch/snmp/mlx/base/acl/acl_template.py

Added support for apply_acl and remove_acl in pyswitch lib.
Below actions were tested as part of this change.
st2 run network_essentials.apply_acl username=admin password=admin mgmt_ip=10.37.73.148 intf_type=ethernet intf_name=1/1,1/3 acl_name=ACL_IP_standard_test acl_direction=in
st2 run network_essentials.remove_acl username=admin password=admin mgmt_ip=10.37.73.148 intf_type=ethernet intf_name=1/1,1/3 acl_name=ACL_MAC_standard_test acl_direction=in
st2 run network_essentials.apply_acl username=admin password=admin mgmt_ip=10.37.73.148 intf_type=ethernet intf_name=1/1,1/3 acl_name=ACL_IP_standard_test acl_direction=in
st2 run network_essentials.remove_acl username=admin password=admin mgmt_ip=10.37.73.148 intf_type=ethernet intf_name=1/1,1/3 acl_name=ACL_IP_standard_test …

Mlx 33 branch

---

pyswitch/snmp/base/acl/acl.py
pyswitch/snmp/base/acl/ipacl.py
pyswitch/snmp/mlx/base/acl/acl.py
pyswitch/snmp/mlx/base/acl/acl_template.py

Added ACL APIs for adding and deleting ipv4 rule to acl.
Following test cases are executed:
* Adding rule to standard ipv4 ACL
-- st2 run network_essentials.add_ipv4_rule_acl username=admin    password=admin  mgmt_ip=10.37.73.148     acl_name=ACL_IP_standard_test action=permit  vlan_id=20 log=False source='1.1.0.0 0.0.255.255'
-- st2 run network_essentials.add_ipv4_rule_acl username=admin    password=admin  mgmt_ip=10.37.73.148     acl_name=ACL_IP_standard_test action=permit source=any
* Adding rule to extended ipv4 ACL
-- st2 run network_essentials.add_ipv4_rule_acl username=admin    password=admin  mgmt_ip=10.37.73.148     acl_name=ACL_IP_extended_test action=permit source=any destination=any protocol_type=iatp dscp=1 dscp_marking=5 fragment=fragment  option=33 suppress_rpf_drop=False …

MLX-33 and MLX-36:

---

pyswitch/AbstractDevice.py
pyswitch/NetConfDevice.py
pyswitch/RestDevice.py
pyswitch/device.py
pyswitch/os/base/services.py
pyswitch/snmp/SnmpMib.py
pyswitch/snmp/mlx/base/services.py

- Pyswitch wrapper for fetching mac address table for MLX
- Cleanup mac_table from Rest and NetConf devices and move it to services class under pyswitch wrapper
Related PR:
https://github.com/StackStorm/network_essentials/pull/195
Test logs on MLX and SLX:
================
ubuntu@st2vagrant:~$ st2 run network_essentials.find_mac mgmt_ip='10.24.85.107' macs='0211.3333.4444' username='admin' password='admin'
.....
id: 5a028728c4da5f41a43d54e2
parameters: 
macs:
- 0211.3333.4444
result: 
exit_code: 0
result:
- interface: ethernet4/1
interface_name: 4/1
interface_type: ethernet
mac_address: 02:11:33:33:44:44
state: active
type: static
vlan: '402'
stderr: 'st2.actions.python.ABCMeta: AUDIT    Creating new Client …

Pyswitch wrapper for MAC table for MLX platform. 

---

pyswitch/os/base/interface.py
pyswitch/snmp/mlx/base/interface.py

1. Pyswitch API for getting a vlan->ports mapping for MLX
2. API to retrieve all VLAN's in system for MLX
3. API to validate if a vlan->port mapping exists on system for MLX. 
4. Also, moved the validation of port-vlan mapping to pyswitch from NE action for NOS/SLX. 
5. Fixed existing issue for SLX/NOS when vlan-range or multiple vlans are provided for validation.
**Test results:**
ubuntu@st2vagrant:~$ st2 run network_essentials.validate_interface_vlan mgmt_ip='10.24.85.102' intf_name='1/0/2' intf_type='tengigabitethernet' intf_mode=trunk vlan_id='15,30'
...
id: 5a06544ec4da5f41a43d5617
parameters: 
intf_mode: trunk
intf_name: 1/0/2
intf_type: tengigabitethernet
mgmt_ip: 10.24.85.102
vlan_id: 15,30
result: 
exit_code: 0
result:
vlan: true
stderr: …

Pyswitch API for getting a vlan->ports mapping, port-vlan validation

---

pyswitch/snmp/base/acl/acl.py
pyswitch/snmp/base/acl/ipv6acl.py
pyswitch/snmp/mlx/base/acl/acl.py
pyswitch/snmp/mlx/base/acl/acl_template.py

Added APIs to pyswitch plugin of MLX to add Ipv6 rules to Ipv6 ACLs.
Following actions are tested successfully.
1. st2 run network_essentials.create_acl username=admin    password=admin  mgmt_ip=10.37.73.148            acl_name=ACL_IPv6_test    acl_type=standard       address_type=ipv6
1. st2 run network_essentials.delete_acl username=admin    password=admin  mgmt_ip=10.37.73.148            acl_name=ACL_IPv6_test
1. st2 run network_essentials.apply_acl username=admin    password=admin  mgmt_ip=10.37.73.148     acl_name=ACL_IPv6_test intf_type=ethernet intf_name=1/1,1/2,1/3,1/5 acl_direction=in
1. st2 run network_essentials.remove_acl username=admin    password=admin  mgmt_ip=10.37.73.148     acl_name=ACL_MAC_standard_test intf_type=ethernet intf_name=1/1 acl_direction=out
1. st2 run …

Mlx 34 63 Ipv6 ACL implementation

---

pyswitch/snmp/mlx/base/interface.py

MAC move detect enable is not supported for MLX, handle the changes in pyswitch
Logs:
ubuntu@st2vagrant:~$ st2 run network_essentials.configure_mac_move_detection mgmt_ip='10.24.85.107' username='admin' password='admin' move_threshold=10
....
id: 5a0bc940c4da5f07cc7fdb40
status: failed
parameters: 
move_threshold: 10
result: 
exit_code: 255
result: None
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.24.85.107.enablepass)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.USER.DEFAULT.enablepass) …

Mac move for MLX

---

pyswitch/snmp/base/acl/acl.py
pyswitch/snmp/base/acl/ipacl.py
pyswitch/snmp/mlx/base/acl/acl.py
pyswitch/snmp/mlx/base/acl/acl_template.py

MLX supports ICMP filter for protocol type ICMP. Added a parameter icmp_filter in action to support this option. Hence adding the code in pyswitch library to handle this parameter.
st2 run network_essentials.add_ipv4_rule_acl username=admin password=admin mgmt_ip=10.37.73.148 acl_name=ACL_IP_extended_test action=permit protocol_type=icmp source='2.2.2.2 0.0.0.255' destination='3.3.3.3 0.0.0.255' icmp_filter='echo-reply'
st2 run network_essentials.add_ipv4_rule_acl username=admin password=admin mgmt_ip=10.37.73.148 acl_name=ACL_IP_extended_test action=permit protocol_type=icmp source='2.2.2.2 0.0.0.255' destination='3.3.3.3 0.0.0.255' icmp_filter='3 0'
NOTE: icmp_filter for type and code is supported for specific combination, user should refer to configuration guide to try such …

Added icmp filter support for ip acl type.

---

pyswitch/snmp/mlx/base/interface.py

Fix for defects MLX-73, MLX-102, MLX-92, MLX-115.
- Handle error scenarios for invalid interface type
Logs:
ubuntu@st2vagrant:~/bash_scripts$ st2 run network_essentials.create_l2_port_channel mgmt_ip='10.24.85.107' username='admin' password='admin' intf_type='tengigabitethernet' ports='2/1/0,2/2/0' mode='standard' protocol='active' port_channel_desc='po50' port_channel_id='50'
......
id: 5a0fa1cec4da5f6616808749
status: failed
parameters: 
intf_type: tengigabitethernet
mode: standard
port_channel_desc: po50
port_channel_id: '50'
ports:
- 2/1/0
- 2/2/0
protocol: active
result: 
exit_code: 255
result: None
No handlers could be found for logger …

Fix for defects MLX-73, MLX-102, MLX-92, MLX-115

---

pyswitch/os/slxos/base/cluster.py

cluster_mgmt_get() makes a REST Call to fetch the details. In standalone mode, REST API does not return 'principal_node_mac'. Fix is to just set an empty string in case of is not available.

CANDY-853 Fix

---

pyswitch/os/slxos/base/cluster.py

In the recent pyswitch lib changes, argument to pyswitch lib REST api has changed which is causing the issue. Update client isolation mode is not working either. So for now, I skipped the client_ioslation_mode programming. It should not have any impact. I will follow up with Brian on the same. Setting this parameter throwing exception now -
YANGBaseClass' object has no attribute '_set_cluster'

Fix Cluster Create

---

pyswitch/snmp/mlx/base/interface.py

logs:
ubuntu@st2vagrant:~/bash_scripts$ st2 run network_essentials.create_l2_port_channel mgmt_ip='10.24.85.107' username='admin' password='admin' intf_type='ethernet' ports='2/1' mode='standard' protocol='modeon' port_channel_desc='po50' port_channel_id='50'
........
id: 5a1eae82c4da5f66168088a8
parameters: 
mode: standard
port_channel_desc: po50
port_channel_id: '50'
ports:
- 2/1
protocol: modeon
result: 
exit_code: 0
result:
port_channel_configs: true
pre_validation: true
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore …

Fix for MLX-167 and MLX-169

---

pyswitch/snmp/mlx/base/interface.py

Logs:
ubuntu@st2vagrant:~/bash_scripts$ st2 run network_essentials.create_ve mgmt_ip='10.24.85.107' username='admin' password='admin' vlan_id='160' ve_id=161  ip_address='161.9.9.4/24'
...................
id: 5a204589c4da5f6616808902
parameters: 
ip_address:
- 161.9.9.4/24
ve_id: '161'
vlan_id: '160'
result: 
exit_code: 0
result:
assign_ip: true
create_ve: true
pre_validation_ip: true
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.24.85.107.enablepass)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore …

Fix for MLX-172

---

pyswitch/snmp/base/acl/ipacl.py
pyswitch/snmp/base/acl/ipv6acl.py
pyswitch/snmp/base/acl/macacl.py

destination is required parameter for extended access-list.
Instead of returning None changed to raise exception.
**Action**:  
st2 run network_essentials.add_ipv4_rule_acl username=admin    password=admin  mgmt_ip=10.37.73.148     acl_name=ACL_IP_extended_test source=any
**Result**: (Partial Output)
...
...
File \"/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages/pyswitch/snmp/mlx/base/acl/acl.py\", line 748, in parse_params_for_add_ipv4_extended\n    user_data['dst_str'] = self.ip.parse_destination(**parameters)\n  File \"/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages/pyswitch/snmp/base/acl/ipacl.py\", line 127, in parse_destination\n    raise ValueError(\"\\'destination\\' is required param for MLX\")\nValueError: 'destination' is …

MLX-147 fix

---

pyswitch/raw/slx_nos/acl/acl_template.py
pyswitch/raw/slx_nos/acl/params_validator.py

device types. Throwing exception if provided.

CANDY-928: Making these parameters as not accepted by slx and vdx

---

pyswitch/snmp/SnmpMib.py

Fix for defects MLX-223,MLX-228,MLX-248.
- Fix the snmp oid issue which was causing validate_vlan to fail. 
- Edit the data type for port-channel id from string to integer in validate_l2_port_channel_state.yaml. With this change only one po id can be entered at a time
- Existing issue where port-channel state validation check is incorrectly computed if there a member port which is out of sync which happens to be computed last and other members of port-channel are in sync.
Logs:
ubuntu@st2vagrant:~/bash_scripts$  st2 run network_essentials.validate_L2_port_channel_state mgmt_ip=10.20.179.132 port_channel_id=1
........
id: 5a377869c4da5f37c54b285c
parameters: 
port_channel_id: 1
result: 
exit_code: 0
result:
member-ports:
- ethernet 8/4
- ethernet …

Fix for defects MLX-223,MLX-228,MLX-248

---

pyswitch/snmp/mlx/base/utils.py

- MLX-252 : Local ping output is different handled that in the code.
- MLX-253:  ping v6 command was incorrect. Earlier this was not tested because of a bug in the st2 platform where ":" input was not handled properly.

Fix for MLX-252 and MLX-253

---

pyswitch/snmp/mlx/base/interface.py
pyswitch/utilities.py

$ st2 run network_essentials.create_vrf mgmt_ip=10.20.179.132 vrf_name="vrf mlx" afi=ipv4 rd=10:240
..........
id: 5a4d9ea8c4da5f0571348104
parameters: 
afi: ipv4
rd: 10:240
vrf_name: vrf mlx
result: 
exit_code: 0
result:
Create_VRF: true
Create_address_family: true
stderr: "st2.actions.python.ABCMeta: AUDIT    Creating new Client object.\nNo handlers could be found for logger \"st2.st2common.services.access\"\nst2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.20.179.132.user)\nst2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.USER.DEFAULT.user)\nst2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore …

create a vrf name with space

---

pyswitch/SnmpCliDevice.py
pyswitchlib/pyswitchlib_api_daemon.py

MLX device connection takes 5-7 seconds. This is an big overhead as every action initiates the connection.  To avoid this overhead moved the netmiko connection to pyswitchlib api daemon. First time connection will take 5-7 seconds and then this connection object will be stored with hash keys user name and password. If there is a change in credentials then the old connection will be deleted and new connection object will be initiated. 
```
ubuntu@bwcvagrant:/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages$ time st2 run network_essentials.ping_vrf_targets mgmt_ip=10.20.179.132 targets=1001::1 vrf=test_ping_vrf count=2 
.....
id: 5a4d34babb0f18081ac6b024
parameters: 
count: 2
targets:
- 1001::1
vrf: test_ping_vrf
result: …
```

MLX-59: Device optimization

---

pyswitch/os/base/utils.py
pyswitch/snmp/mlx/base/utils.py

- Fix the json output and also fail the status even if one target fails.
The below mentioned PR in NE pack will be complete fix:
https://github.com/StackStorm/network_essentials/pull/263
***SLX failure case***
```
ubuntu@bwcvagrant:/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages$ time st2 run network_essentials.ping_vrf_targets mgmt_ip=10.24.86.96 targets=10.20.179.132,10.24.89.109 count=2 vrf=mgmt-vrf
..............
id: 5a4eb01fbb0f18081ac6b096
status: failed
parameters: 
count: 2
mgmt_ip: 10.24.86.96
targets:
- 10.20.179.132
- 10.24.89.109
vrf: mgmt-vrf
result: 
exit_code: 0
result:
- ip_address: 10.24.89.109
packet loss: 100%
packets received: 0
packets transmitted: 2
result: fail
- ip_address: 10.20.179.132
packet loss: 0%
packets received: 2
packets …
```

Ping vrf fix

---

pyswitch/raw/slx_nos/acl/aclparam_parser.py
pyswitch/raw/slx_nos/acl/params_validator.py

Raising exception if rbridge-id is specified for non-ve and non-loopback
interface types.

CANDY-869: Added traffic_type check in params validator.

---

pyswitch/snmp/SnmpMib.py
pyswitch/snmp/mlx/base/interface.py

Fix for defects MLX-216, MLX-217, MLX-218, MLX-219, MLX-221
ubuntu@st2vagrant:~/bash_scripts$ st2 run network_essentials.validate_interface_state mgmt_ip=10.24.85.107 username='admin' password='admin' intf_type=ethernet intf_name=4/3 intf_state=up
..
id: 5a564fb2c4da5f37c54b29bd
parameters: 
intf_name: 4/3
intf_state: up
result: 
exit_code: 0
result:
intf: true
state: up
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.24.85.107.enablepass)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore …

validate interface state for MLX

---

pyswitch/device.py
pyswitchlib/pyswitchlib_api_daemon.py

- Fix stale connection issues
- Reduce snmp timeout and retries for performance improvement
```
Tests:
- Run a st2 action on mlx device.
- Rerun the action on same device and ensure connection is intact
- Reboot the MLX device
- Rerun the action on same device and ensure no Devicecommunication error.
```

MLX-268: Fix the stale connection issue when DUT is rebooted

---

pyswitch/raw/nos/base/acl/acl.py
pyswitch/raw/slxos/base/acl/acl.py
pyswitch/raw/slxos/ver_17s/acl.py

stackstorm converts vlan or ve interface names to integers and hence
check fails against netconf response. typecasting interface name to str.

CANDY-1028

---

pyswitch/snmp/mlx/base/interface.py

MLX gives different output for same "show interface ethernet <>" command when a interface part of port-channel, so changed regex search to be common for both
st2 run network_essentials.remove_switchport_access_vlan mgmt_ip=10.20.179.132 intf_type=port_channel intf_name=200 vlan_id=200
.....
id: 5a5fce17c4da5f5f037f199d
parameters: 
intf_name: '200'
intf_type: port_channel
vlan_id: '200'
result: 
exit_code: 0
result: true
stderr: 'st2.actions.python.RemoveSwitchPort: DEBUG    Creating new Client object.
st2.actions.python.RemoveSwitchPort: DEBUG    Retrieving value from the datastore (name=switch.10.20.179.132.user)
st2.actions.python.RemoveSwitchPort: DEBUG    Retrieving value …

Changed regex search to remove access vlan for both po and ethernet

---

pyswitch/snmp/mlx/base/interface.py

Logs:
ubuntu@st2vagrant:~/bash_scripts$ st2 run network_essentials.validate_interface_vlan mgmt_ip=10.20.179.132 vlan_id=200 intf_type=port_channel intf_name=200 intf_mode=trunk
...
id: 5a5e2bd5c4da5f37c54b2b0a
parameters: 
intf_mode: trunk
intf_name: '200'
intf_type: port_channel
vlan_id: '200'
result: 
exit_code: 0
result:
vlan: true
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.20.179.132.user)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.USER.DEFAULT.user)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the …

Fix for defects MLX-270, MLX-271,MLX-273, MLX-274,MLX-275

---

pyswitch/snmp/mlx/base/interface.py
pyswitch/snmp/mlx/base/system.py

$ st2 run network_essentials.set_l3_system_mtu mgmt_ip=10.24.85.107 username=admin password=admin mtu_size=9198 afi=ipv6
.......
id: 5a66554fc4da5f5f037f19cd
parameters: 
afi: ipv6
mtu_size: 9198
result: 
exit_code: 0
result:
result: true
stderr: 'st2.actions.python.set_l3_system_mtu: DEBUG    Creating new Client object.
st2.actions.python.set_l3_system_mtu: DEBUG    Retrieving value from the datastore (name=switch.10.24.85.107.enablepass)
st2.actions.python.set_l3_system_mtu: DEBUG    Retrieving value from the datastore (name=switch.USER.DEFAULT.enablepass)
st2.actions.python.set_l3_system_mtu: DEBUG    Retrieving value from the datastore …

Maximum IP MTU value changed for MLX

---

pyswitch/raw/slx_nos/acl/macacl.py
pyswitch/raw/slxos/base/acl/acl.py

Fusion platform suports ethertype ipv6 whereas vdx doesn't. The earlier
implementation was influenced by vdx. This change allows ipv6 ethertype
for fusion device type.

CANDY-1026

---

pyswitch/SnmpCliDevice.py
pyswitch/snmp/base/interface.py

snmp-set/get/walk was not raising an exception for failure cases. Raise the exception.
Logs:
ubuntu@st2vagrant:~/bash_scripts$ st2 run network_essentials.delete_vlan mgmt_ip=10.18.121.2 username=User_test password=password vlan_id=10
.....
id: 5a750471c4da5f37c54b2b61
status: failed
parameters: 
mgmt_ip: 10.18.121.2
username: User_test
vlan_id: '10'
result: 
exit_code: 255
result: None
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.18.121.2.enablepass)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.USER.DEFAULT.enablepass) …

Fix for MLX-282

---

pyswitch/raw/base/acl.py
pyswitch/raw/nos/base/acl/acl.py
pyswitch/raw/nos/base/acl/acl_template.py
pyswitch/raw/slx_nos/acl/acl.py
pyswitch/raw/slx_nos/acl/acl_template.py
pyswitch/raw/slx_nos/acl/params_validator.py
pyswitch/raw/slxos/base/acl/acl.py
pyswitch/raw/slxos/ver_17s/acl.py
pyswitch/snmp/base/acl/acl.py
pyswitch/snmp/mlx/base/acl/acl.py

NOTE: This only avaliable to NOS device type as part of this commit.
Following cases executed as part of this commit:
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.37.18.151 acl_name=ext-l2-acl-bulk acl_rules='[{"action": "deny", "source": "1111.1111.1111", "src_mac_addr_mask": "1111.1111.1111", "dst": "1111.1111.1111", "dst_mac_addr_mask": "1111.1111.1111"}, {"action": "deny", "source": "1111.1111.1112", "src_mac_addr_mask": "1111.1111.1112", "dst": "1111.1111.1112", "dst_mac_addr_mask": "1111.1111.1112"}, {"action": "deny", "source": "1111.1111.1113", "src_mac_addr_mask": "1111.1111.1113", "dst": "1111.1111.1113", "dst_mac_addr_mask": "1111.1111.1113"}]'
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.37.18.151 acl_name=ext-l2-acl-bulk delete=True …

L2 bulking support added for action add_or_remove_l2_acl_rule.

---

pyswitch/raw/slxos/base/acl/acl.py
pyswitch/raw/slxos/base/acl/acl_template.py

Actions Executed are:
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.20.179.147 acl_name=ext-l2-acl-bulk acl_rules='[{"action": "deny", "source": "1111.1111.1111", "src_mac_addr_mask": "1111.1111.1111", "dst": "1111.1111.1111", "dst_mac_addr_mask": "1111.1111.1111"}, {"action": "deny", "source": "1111.1111.1112", "src_mac_addr_mask": "1111.1111.1112", "dst": "1111.1111.1112", "dst_mac_addr_mask": "1111.1111.1112"}, {"action": "deny", "source": "1111.1111.1113", "src_mac_addr_mask": "1111.1111.1113", "dst": "1111.1111.1113", "dst_mac_addr_mask": "1111.1111.1113"}]'
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.20.179.147 acl_name=ext-l2-acl-bulk delete=True seq_id="101,102,103-110,115-"
st2 run network_essentials.add_or_remove_l2_acl_rule …

L2 Bulk support added for SLX device type.

---

pyswitch/raw/slxos/ver_17s/acl.py
pyswitch/raw/slxos/ver_17s/acl_template.py

Actions executed are:
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.24.85.103 acl_name=ext-l2-acl-bulk  acl_rules='[{"action": "deny", "source": "1111.1111.1111", "src_mac_addr_mask": "1111.1111.1111", "dst": "1111.1111.1111", "dst_mac_addr_mask": "1111.1111.1111"}, {"action": "deny", "source": "1111.1111.1112", "src_mac_addr_mask": "1111.1111.1112", "dst": "1111.1111.1112", "dst_mac_addr_mask": "1111.1111.1112"}, {"action": "deny", "source": "1111.1111.1113", "src_mac_addr_mask": "1111.1111.1113", "dst": "1111.1111.1113", "dst_mac_addr_mask": "1111.1111.1113"}]'
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.24.85.103 acl_name=ext-l2-acl-bulk delete=True seq_id="10,20-"
st2 run network_essentials.add_or_remove_l2_acl_rule mgmt_ip=10.24.85.103 …

L2 Bulk support added for SLX 17s devices.

---

pyswitch/os/nos/base/system.py

Pyswitch API 'device.system.chassis_name' was always fetching the model_type of the first switch in vcs cluster since the API was not coded to accept the rbridge_id as the input args .
Fixed this now to return the model_type based on the rbridge_id.

CANDY-1061: Passing the right model type in a vcs cluster

---

pyswitch/snmp/mlx/base/interface.py

Removed a CLI-set callback which was causing delay during VLAN creation.

Fix for defect MLX-296

---

pyswitch/snmp/mlx/base/interface.py

vagrant (intf_error *) PySwitchLib
$  st2 run network_essentials.set_intf_admin_state mgmt_ip=10.20.179.132 intf_type=ethernet intf_name=1/1
..
id: 5a7cebf9c4da5f04e0bb3698
status: failed
parameters: 
intf_name: 1/1
result: 
exit_code: 1
result: None
stderr: "st2.actions.python.SetIntfAdminState: DEBUG    Creating new Client object.\nNo handlers could be found for logger \"st2.st2common.services.access\"\nst2.actions.python.SetIntfAdminState: DEBUG    Retrieving value from the datastore (name=switch.10.20.179.132.user)\nst2.actions.python.SetIntfAdminState: DEBUG    Retrieving value from the datastore (name=switch.USER.DEFAULT.user)\nst2.actions.python.SetIntfAdminState: DEBUG    Retrieving value from the datastore …

Error message changed similar to SLX/NOS:MLX-290

---

pyswitch/os/base/interface.py

Fixing the issue in pyswitch wrapper API where logic works only for system default config resulting in mac-move detection configuration fails after disabling the same. 
vagrant@st2vagrant:/opt/stackstorm/virtualenvs/network_essentials/lib$ st2 run network_essentials.configure_mac_move_detection mgmt_ip="10.24.86.96" username="admin" password="password"
......
id: 5a83404ac4da5f04d600ddb0
parameters: 
mgmt_ip: 10.24.86.96
result: 
exit_code: 0
result:
conv-arp: true
stderr: 'st2.actions.python.ConfigureMacMoveDetection: INFO     successfully connected to 10.24.86.96
st2.actions.python.ConfigureMacMoveDetection: INFO     Configuring Mac Move Detect Enable
st2.actions.python.ConfigureMacMoveDetection: INFO     Configuring Mac Move …

Mac Move Detection Fix

---

pyswitch/SnmpCliDevice.py
pyswitch/snmp/mlx/base/interface.py
pyswitchlib/pyswitchlib_api_daemon.py

- Obtained device level lock to simultaneously execute the action
- Moved lock acquire to pyswitch_api_dameon
-Fix performance issue in create vlan

MLX-293: Obtain device level lock in api daemon to unblock other actions in case of timeout

---

pyswitch/AbstractDevice.py
pyswitch/NetConfDevice.py
pyswitch/RestDevice.py
pyswitch/SnmpCliDevice.py
pyswitch/device.py
pyswitchlib/pyswitchlib_api_daemon.py

$ st2 run network_essentials.validate_vrrpe_state mgmt_ip=10.24.85.107 intf_type=ethernet intf_name=2/6 vrrpe_group=1 username=admin password=admi
...
id: 5a8f7373c4da5f04bd1c27fc
status: failed
parameters: 
intf_name: 2/6
mgmt_ip:
- 10.24.85.107
username:
- admin
vrrpe_group: '1'
result: 
exit_code: 0
result:
reason: '[Netmiko Authentication Exception:] Authentication failure: unable to connect brocade_netiron 10.24.85.107:22
Authentication failed.'
reason_code: 2
stderr: 'st2.actions.python.validate_vrrpe_state: DEBUG    Creating new Client object.
st2.actions.python.validate_vrrpe_state: DEBUG    Retrieving value from the datastore (name=switch.10.24.85.107.user) …

Authentication and deviceCommerror exception is added MLX-300

---

pyswitch/snmp/mlx/base/interface.py

- Address the VRF assignment of VE with spaces during VE creation/deletion 
ubuntu@st2vagrant:~$ st2 run network_essentials.create_ve mgmt_ip='10.24.85.107' username='admin' password='admin' vlan_id=21 ve_id=21 vrf_name="vrf ext1" ipv6_use_link_local_only=True ip_address=21.7.7.7/24
...............
id: 5a904bdfc4da5f0fff31ef4a
parameters: 
ip_address:
- 21.7.7.7/24
ipv6_use_link_local_only: true
ve_id: '21'
vlan_id: '21'
vrf_name: vrf ext1
result: 
exit_code: 0
result:
assign_ip: true
create_ve: true
pre_validation_ip: true
pre_validation_vrf: true
vrf_configs: true …

Fix for defect mlx-318

---

pyswitch/AbstractDevice.py
pyswitch/NetConfDevice.py
pyswitch/RestDevice.py
pyswitch/SnmpCliDevice.py
pyswitch/device.py

device has platform_type property added which will provide the chassis name values for slx and vdx devices. For MLX refer  pyswitch/snmp/snmpconnector.py
This has been fixed only for snmpcli and rest devices. For netconf , there is no operational data support to retrieve chassis name value.
```
ubuntu@bwcvagrant:/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages/netmiko$ time st2 run network_essentials.create_ve mgmt_ip=10.24.81.125 vlan_id=23 ve_id=23 username=admin password=password
.....
id: 5a8fad55bb0f180b935f377e
parameters: 
mgmt_ip: 10.24.81.125
ve_id: '23'
vlan_id: '23'
result: 
exit_code: 0
result: {}
stderr: 'st2.actions.python.CreateVe: DEBUG    Creating new Client object.
No handlers could be found …
```

Add platform type information in device context

---

pyswitch/snmp/mlx/base/interface.py

- Capture the error and print it when the vlan creation fails due to insufficient vlan ids. Also print the first VLAN that is failing.
logs:
ubuntu@st2vagrant:~$ st2 run network_essentials.create_vlan mgmt_ip=10.24.85.107 username=admin password=admin vlan_id=515-517
........
id: 5a965e39c4da5f0fff31f05e
status: failed
parameters: 
vlan_id: 515-517
result: 
exit_code: 255
result: None
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.24.85.107.restproto)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore …

Fix for mlx-295

---

pyswitch/snmp/mlx/base/interface.py

Optimize vlan by removing redundant call to switch.
```
ubuntu@bwcvagrant:/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages$ time st2 run network_essentials.create_vlan mgmt_ip=10.24.85.107 username=admin password=admin vlan_id=2-501
..................................
id: 5a988f66bb0f180b935f37c9
parameters: 
vlan_id: 2-501
result: 
exit_code: 0
result:
vlan: true
stderr: 'st2.actions.python.CreateVlan: DEBUG    Creating new Client object.
No handlers could be found for logger "st2.st2common.util.api"
st2.actions.python.CreateVlan: DEBUG    Retrieving value from the datastore (name=switch.10.24.85.107.restproto)
st2.actions.python.CreateVlan: DEBUG    Retrieving value from the datastore …
```

remove redundant call to switch

---

pyswitchlib/asset.py

Contains fixes for MLX-334, MLX-335, and MLX-338.
MLX-334:
A more descriptive RestInterfaceError is raised.
MLX-335/338:
Suppressed SubjectAltName warnings since VDX/SLX does not support creating certificates with SubjectAltNames.  The CommonName set to switches' IP address will be used.

Fixed HTTPS Warnings.

---

pyswitch/os/base/interface.py
pyswitch/raw/nos/base/interface.py
pyswitch/raw/nos/base/template.py
pyswitch/raw/slxos/base/interface.py
pyswitch/raw/slxos/base/template.py
pyswitch/snmp/base/interface.py

- Call to NetConf instead of Rest API to reduce time taken to delete the VLAN's.
Logs:
===
ubuntu@st2vagrant:~$ st2 run network_essentials.delete_vlan mgmt_ip=10.24.81.183 username=admin password=password vlan_id=2000-2500
...............................
id: 5a9e0d35c4da5f0fff31f2a1
parameters: 
mgmt_ip: 10.24.81.183
vlan_id: 2000-2500
result: 
exit_code: 0
result:
vlan: true
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.24.81.183.restproto)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.USER.DEFAULT.restproto) …

MLX-337 VLAN delete optimizations

---

pyswitch/snmp/mlx/base/interface.py
pyswitch/utilities.py

- Add util function to validate portchannel id range for all platforms (SLX, VDX, NI)
ubuntu@st2vagrant:~$ st2 run network_essentials.delete_l2_port_channel mgmt_ip='10.24.12.106' username='admin' password='password' port_channel_id=65
..
id: 5aa07138c4da5f0fff31f3f1
status: failed
parameters: 
mgmt_ip: 10.24.12.106
port_channel_id: 65
result: 
exit_code: 255
result: None
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.10.24.12.106.restproto)
st2.actions.python.ABCMeta: AUDIT    Retrieving value from the datastore (name=switch.USER.DEFAULT.restproto) …

Add util function to validate po id range for all platforms

---

pyswitch/os/base/utils.py
pyswitch/snmp/mlx/base/utils.py

Modified ping output based on the rules defined in MLX-297. 
```
ubuntu@bwcvagrant:~$ st2 run network_essentials.ping_vrf_targets mgmt_ip=10.24.81.125 targets=10.24.12.106,10.24.85.107 vrf=mgmt-vrf count=4 
.........
id: 5aa0e3c7bb0f18254ae85fae
parameters: 
count: 4
mgmt_ip: 10.24.81.125
targets:
- 10.24.12.106
- 10.24.85.107
vrf: mgmt-vrf
result: 
exit_code: 0
result:
output:
- ip_address: 10.24.85.107
packet loss: 0%
packets received: 4
packets transmitted: 4
result: pass
- ip_address: 10.24.12.106
packet loss: 0%
packets received: 4
packets transmitted: 4
result: pass
reason_code: 0
stderr: 'st2.actions.python.CheckPing: DEBUG    Creating new Client object.
No handlers could be found for logger "st2.st2common.util.api"
st2.actions.python.CheckPing: DEBUG …
```

MLX-367: modify ping returns based on the validate rules defined

---

pyswitch/utilities.py

Logs:
ubuntu@st2vagrant:~$ st2 run network_essentials.create_l2_port_channel intf_type=ethernet ports=1/6 port_channel_id=513 mgmt_ip=10.17.113.52 username=admin password=password port_channel_desc="po103"
..
id: 5aab08d5c4da5f214afc7330
status: failed
parameters: 
mgmt_ip: 10.17.113.52
port_channel_desc: po103
port_channel_id: '513'
ports:
- 1/6
result: 
exit_code: 255
result: None
stderr: 'st2.actions.python.CreatePortChannel: DEBUG    Creating new Client object.
st2.actions.python.CreatePortChannel: DEBUG    Retrieving value from the datastore (name=switch.10.17.113.52.restproto)
st2.actions.python.CreatePortChannel: DEBUG    Retrieving value from the datastore …

Fix for MLX-385: Add platform type for Fusion F4 for PO ID range check

---

pyswitch/raw/nos/base/acl/acl.py
pyswitch/raw/slx_nos/acl/ipxacl.py

Changed vlan range from 4095 to 8191 for nos devices.
Action:
-------
st2 run network_essentials.add_ipv6_rule_acl mgmt_ip=10.20.61.37 acl_name=new_ipv6_acl1 action=permit protocol_type=tcp source=7:46::/128 destination=6:56::/128 seq_id=103 vlan_id=8190
Verified:
---------
do show running-config ipv6 access-list extended
ipv6 access-list extended new_ipv6_acl1
seq 103 permit tcp 7:46::/128 6:56::/128 vlan 8190

CANDY-1125

---

pyswitch/raw/nos/base/acl/acl.py

Added a meaningful error for access-list configuration on Ve interface when
rbrid-id was not provided.
Action:
--------
st2 run network_essentials.apply_acl mgmt_ip=10.20.61.37 acl_name=xyz  intf_type=ve intf_name=999 acl_direction=in rbridge_id=37
Verified:
---------
show running-config rbridge-id interface Ve 999
rbridge-id 37
interface Ve 999
ipv6 access-group xyz in
shutdown
!
!
Action:
--------
st2 run network_essentials.apply_acl mgmt_ip=10.20.61.37 acl_name=xyz  intf_type=ve intf_name=999 acl_direction=in
Verified:
---------
Traceback (most recent call last):
File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 316, in <module>
obj.run()
File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 178, in run
output …

CANDY-1127

---

pyswitch/os/base/utils.py
pyswitch/snmp/mlx/base/utils.py

Tests:
```
ubuntu@bwcvagrant:~$ st2 run network_essentials.ping_vrf_targets mgmt_ip=10.24.12.106 targets=10.17.113.185  vrf=default-vrf size=31955
...
id: 5abb36cabb0f18390278986f
status: failed
parameters: 
mgmt_ip: 10.24.12.106
size: 31955
targets:
- 10.17.113.185
vrf: default-vrf
result: 
exit_code: 0
result:
reason: Invalid size - valid range 0 to 31954
reason_code: 1
stderr: 'st2.actions.python.CheckPing: DEBUG    Creating new Client object.
No handlers could be found for logger "st2.st2common.util.api"
st2.actions.python.CheckPing: DEBUG    Retrieving value from the datastore (name=switch.10.24.12.106.restproto)
st2.actions.python.CheckPing: DEBUG    Retrieving value from the datastore (name=switch.10.24.12.106.user)
st2.actions.python.CheckPing: DEBUG    Retrieving value from the …
```

MLX-395 - Fix the range checks for ping size and timeout

---

pyswitch/raw/nos/base/interface.py
pyswitch/raw/nos/base/template.py
pyswitch/raw/slxos/base/interface.py
pyswitch/raw/slxos/base/template.py

Below netconf templates are added to configure the interface properties:
1. mtu
2. ip_mtu
3. bfd interval
4. ip address (unnumbered also)
5. ip proxy-arp
6. ipv6_mtu (SLX only)
7. fabric isl enable (VDX only)
8. fabric trunk enable (VDX only)
9. fabric neighbor discovery disable (VDX only)
10. no switchport
11. no shutdown
12. Loopback creation

Candy 1120

---

pyswitch/utilities.py

$  st2 run network_essentials.create_switchport_trunk intf_type=ethernet mgmt_ip=10.20.179.147 intf_name=1/9 vlan_id=4090
...
id: 5abe8423c4da5f04c308225f
parameters: 
intf_name: 1/9
mgmt_ip: 10.20.179.147
vlan_id: '4090'
result: 
exit_code: 0
result:
switchport_doesnot_exists: true
switchport_trunk_config: true
switchport_trunk_vlan_config: true
stderr: 'st2.actions.python.CreateSwitchPort: DEBUG    Creating new Client object.
No handlers could be found for logger "st2.st2common.util.api"
st2.actions.python.CreateSwitchPort: DEBUG    Retrieving value from the datastore (name=switch.10.20.179.147.restproto)
st2.actions.python.CreateSwitchPort: DEBUG    Retrieving value from the datastore (name=switch.10.20.179.147.user) …

Reserved VLAN  is not required NI  MLX-399

---

pyswitch/raw/nos/base/acl/acl_template.py

Verified that action is working.
Action:
--------
st2 run network_essentials.add_ipv4_rule_acl mgmt_ip=10.20.61.41 acl_name=new_ip_acl1 acl_rules='[{"action": "permit", "source": "4.47.0.0/0.255.255.255 eq bootps","destination":"9.57.0.0/0.0.255.255 lt snmp","protocol_type":"udp" ,"seq_id":118}]'
Verified:
---------
id: 5ac1d791e3c93b604f85ed0e
parameters:
acl_name: new_ip_acl1
acl_rules:
- action: permit
destination: 9.57.0.0/0.0.255.255 lt snmp
protocol_type: udp
seq_id: 118
source: 4.47.0.0/0.255.255.255 eq bootps
mgmt_ip: 10.20.61.41

Fixing typo error in temnplate file.

---

pyswitch/raw/nos/base/interface.py

If the interface is pre-configured with ip numbered, re-running the action will attempt to re-configure and action fails due to 'NSM_ERR_IPUNNUMBERED_ALREADY_CONFIGURED | %Error: IP Unnumbered interface configuration is already done on this interface.' . there is no check to catch this exception which subsequently fails the action . 
Added a check to catch this exception and print the message.  The check is only added for ip numbered. 
Previous Behavior
-------------------
[root@win7test vagrant]# st2 run dcfabric.configure_intfs_ipfabric host=10.37.18.166 interfaces='[{"interface":"tengigabitethernet1/1/1", "ip":"unnumbered", "rbridge_id":"1", "donor":"loopback1"}]' bfd_tx=50 bfd_rx=100 bfd_multiplier=10
..
id: 5ad6d9cfc40775300a429570
status: failed
parameters:
bfd_multiplier: '10' …

idempotent check for ip numbered
